# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class Pet(BaseModel):
    """Pet

    :param id_: id_
    :type id_: int
    :param name: name
    :type name: str
    :param tag: tag, defaults to None
    :type tag: str, optional
    """

    def __init__(self, id_: int, name: str, tag: str = None):
        """Pet

        :param id_: id_
        :type id_: int
        :param name: name
        :type name: str
        :param tag: tag, defaults to None
        :type tag: str, optional
        """
        self.id_ = id_
        self.name = name
        self.tag = self._define_str("tag", tag, nullable=True)
